export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const EMPLOYEE_LOGIN = "EMPLOYEE_LOGIN";
export const EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE";
export const ADD_TOKEN = "ADD_TOKEN";
export const LOGOUT_USER = 'LOGOUT_USER';
